api_platform:
    use_symfony_listeners: true
    keep_legacy_inflector: false
    title: Hello FourData !
    description: 'Welcome to the FourData API'
    version: 1.0.0
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
        html: ['text/html']
        
