version: '3.8'

services:

  www:
    restart: unless-stopped
    image: nginx:alpine
    container_name: www
    ports:
      - "8000:80"
    volumes:
      - .:/var/www:delegated
      - ./tools/docker/web/config.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
    restart: unless-stopped
    image: lucasluk798/php:8.2
    container_name: php
    volumes:
      - .:/var/www:delegate
    environment:
      APP_ENV: dev
  
  database:
    image: mysql:8.0
    container_name: database
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fourdata
    volumes:
      - ./var:/var/www/var
      - ./tools/docker/mysql:/var/lib/mysql

networks:
  dev:

  
